### ISSUE TITLE
Profiles tab crash

### ISSUE THREAD

**Issue by proteriax** [ProtonVPN/android-app#14]
App version: 2.0.25
Android version: Android 10

Crash log:
```
03-09 14:08:21.754  7753  7753 E AndroidRuntime: FATAL EXCEPTION: main
03-09 14:08:21.754  7753  7753 E AndroidRuntime: Process: ch.protonvpn.android, PID: 7753
03-09 14:08:21.754  7753  7753 E AndroidRuntime: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter server
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at com.protonvpn.android.ui.home.profiles.ProfilesViewModel.getConnectTextRes(Unknown Source:2)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at com.protonvpn.android.ui.home.profiles.ProfilesAdapter$ServersViewHolder.bindData(ProfilesAdapter.java:119)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at com.protonvpn.android.ui.home.profiles.ProfilesAdapter.onBindViewHolder(ProfilesAdapter.java:69)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at com.protonvpn.android.ui.home.profiles.ProfilesAdapter.onBindViewHolder(ProfilesAdapter.java:47)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
03-09 14:08:21.754  7753  7753 E AndroidRuntime:  at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
```

[Culprit is here.](https://github.com/ProtonVPN/android-app/blob/master/app/src/main/java/com/protonvpn/android/ui/home/profiles/ProfilesAdapter.java#L119) Recommended fix:

```diff
119c119,121
<             buttonConnect.setText(profilesViewModel.getConnectTextRes(server));
---
>             if (server != null) {
>                 buttonConnect.setText(profilesViewModel.getConnectTextRes(server));
>             }

```

**Comment by mateusz-markowicz** [comment]
Thank you for reporting. This is now fixed in our internal repo and will be available on github with next stable release.
